---
- name: copy filebeat.deb
  copy:
    src: filebeat-8.9.0-amd64.deb
    dest: /tmp
    
- name: install filebeat
  apt:
    deb: "/tmp/filebeat-8.9.0-amd64.deb"
    
- name: replace config file
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
  notify:
    - enable filebeat
        
- name: setup filebeat
  shell: 'filebeat setup'
